#数据集文件路径
patch_path: './01-data/02-乳腺癌/01-gen-patch/'
exp_label_path: './01-data/02-乳腺癌/08-update-gene-exp-label/'
orig_path: './01-data/02-乳腺癌/09-update-orig_exp/'

#测试数据集路径
test_patch_path: ./01-data/02-乳腺癌/07-验证的breast-tiff/01-gen-patch/
test_label_path: ./01-data/02-乳腺癌/07-验证的breast-tiff/02-gene-exp-label/breast_gene.json
test_orig_path: ./01-data/02-乳腺癌/07-验证的breast-tiff/04-orig_exp/

#测试样本
num_gene: 821
test_index: 0

#模型定义
model_name: 'SciSt'
img_encoder: 'resnet34'
model_output_num: 1
wts_path:

#训练配置
batch_size: 32
epoch: 81
num_workers: 20
lr: 1e-5
betas: (0.9, 0.999)
loss_func: nn.MSELoss()
loss_coefficient: 0.8 #最后输出的loss占总loss的比例
log_step_freq: 20

#保存路径
output_path: './03-without_TCGN_as_ImgEncoder/03-CNN-SASM/FINAL_MODEL_Breast/retrain_without_earlystop/'