#数据集文件路径
patch_path: './01_patch/'
exp_label_path: './02_label/'
orig_path: './06-noise_exp/'

#测试样本
num_gene: 785
test_index: 0

#模型定义
model_name: 'SciSt'
img_encoder: 'resnet34'
wts_path:

#训练配置
batch_size: 32
epoch: 81
num_workers: 20
loss_coefficient: 0.8 #最后输出的loss占总loss的比例
log_step_freq: 20

#保存路径
output_path: './07-SciSt/'